version: '3'

services:
  xrayr:
    image: jat001/xrayr:latest
    ports:
      # mark sure `offset_port_node` on sspanel is this port
      - '443:443'
    volumes:
      - ./conf.d:/etc/xrayr/conf.d
      - ./node.d:/etc/xrayr/node.d
      - xrayr:/tmp/xrayr
    restart: always

volumes:
  xrayr:
